### ISSUE TITLE
Update code to latest version of Function runtime & binding support

### ISSUE THREAD

**Issue by Jandev** [Jandev/azurefunctions-sqlbinding#4]
The code has been created a long time ago. In the mean time the runtime & binding support has changed a small bit.

The code should be updated to the latest runtime and use the latest binding features.

**Comment by jayendranarumugam** [comment]
Hi @Jandev , I've updated the code with the latest runtime https://github.com/Jandev/azurefunctions-sqlbinding/pull/10 . However not too sure about the latest binding features. Can you help me here ?

**Comment by Jandev** [comment]
I've did some searching and it appears the Binding functionality still works the same on the new runtime. All should be good then.
If you publish your PR, I'll approve it asap.

**Comment by jayendranarumugam** [comment]
The PR https://github.com/Jandev/azurefunctions-sqlbinding/pull/10 is live now
