### ISSUE TITLE
Add image/logo to project / Nuget package

### ISSUE THREAD

**Issue by Jandev** [Jandev/azurefunctions-sqlbinding#5]
This project and package doesn't has an image or logo attached to the Nuget package.

A simple logo has to be created and added to the package.

**Comment by Druffl3** [comment]
What kind of a logo are you expecting?

**Comment by Jandev** [comment]
Earlier today a logo was provided in one of my other packages, which suffices nicely.
The other issue (and corresponding PR) can be found over here: https://github.com/Jandev/azurefunctions-httpbinding/issues/6

**Comment by jayendranarumugam** [comment]
Looks like a simple one. I just did a PR https://github.com/Jandev/azurefunctions-sqlbinding/pull/9 can you check whether is this fine?
